name = "supcoba"
main = "supjav6.ts"
compatibility_date = "2023-02-01"

[vars]

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = false




# Tambahkan variabel lingkungan jika ada









