name = "supcoba"
compatibility_date = "2023-02-01"
main = "supjav22.ts"
[vars]

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = false




# Tambahkan variabel lingkungan jika ada































